"""Cluster-wide node utilization grid widget."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple

import colorsys

from rich.console import Group, RenderableType
from rich.text import Text
from textual.containers import VerticalScroll
from textual.message import Message
from textual.widget import Widget
from textual.widgets import Static

from .data import Job, SchedulerSnapshot
from .nodes import parse_node_count_spec, extract_exec_host_nodes, extract_requested_nodes

# ── colour palette ──────────────────────────────────────────────────────

# Theme variable names used as seed colours for job blocks.
# Variations are generated by shifting hue to produce a large distinct palette.
_THEME_SEED_KEYS = [
    "primary", "secondary", "accent", "warning", "error", "success", "boost",
]

# Fallback hex colours when theme variables are unavailable
_FALLBACK_SEEDS = [
    "#4DB2FF", "#89DDFF", "#F8BD96", "#F9E2AF", "#F38BA8", "#94E2D5", "#CBA6F7",
]


def _hex_to_rgb(h: str) -> Tuple[int, int, int]:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _rgb_to_hex(r: int, g: int, b: int) -> str:
    return f"#{r:02x}{g:02x}{b:02x}"


def _darken(hex_color: str, factor: float = 0.35) -> str:
    """Return a darker variant of *hex_color*."""
    r, g, b = _hex_to_rgb(hex_color)
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    l = max(0.0, l * (1 - factor))
    r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
    return _rgb_to_hex(int(r2 * 255), int(g2 * 255), int(b2 * 255))



def _desaturate(hex_color: str, factor: float = 0.5) -> str:
    """Return a muted/desaturated variant of *hex_color*."""
    r, g, b = _hex_to_rgb(hex_color)
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    s = s * (1 - factor)
    l = min(1.0, l * 0.7 + 0.15)  # push toward mid-range
    r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
    return _rgb_to_hex(int(r2 * 255), int(g2 * 255), int(b2 * 255))



# ANSI colors as the primary job palette — maximum contrast, works everywhere
_ANSI_JOB_STYLES = [
    "on blue",
    "on red",
    "on green",
    "on magenta",
    "on cyan",
    "on yellow",
    "on bright_blue",
    "on bright_red",
    "on bright_green",
    "on bright_magenta",
    "on bright_cyan",
    "on bright_yellow",
    "on white",
    "on bright_black",
]

def _build_palette(theme_vars: Dict[str, str]) -> "Palette":
    """Build a colour palette using ANSI colors + theme surface for empties."""
    surface = theme_vars.get("surface", "#141B2D").strip()
    if not surface.startswith("#"):
        surface = "#141B2D"

    # For aggregated queues: desaturate the theme seeds for muted tones
    seeds: List[str] = []
    for key in _THEME_SEED_KEYS:
        val = theme_vars.get(key, "").strip()
        if val and val.startswith("#"):
            seeds.append(val)
    if not seeds:
        seeds = list(_FALLBACK_SEEDS)
    agg_colors = [_desaturate(s, 0.6) for s in seeds]

    return Palette(
        job_styles=list(_ANSI_JOB_STYLES),
        agg_colors=agg_colors,
        empty_style=f"on {_darken(surface, 0.05)}",
    )


class Palette:
    """Resolved colour palette for the cluster grid."""

    __slots__ = ("job_styles", "agg_colors", "empty_style")

    def __init__(
        self,
        job_styles: List[str],
        agg_colors: List[str],
        empty_style: str,
    ) -> None:
        self.job_styles = job_styles
        self.agg_colors = agg_colors
        self.empty_style = empty_style

    def job_style(self, idx: int) -> str:
        return self.job_styles[idx % len(self.job_styles)]

    def agg_style(self, queue_name: str) -> str:
        """Return a style for an aggregated queue."""
        i = hash(queue_name) % len(self.agg_colors)
        return f"on {self.agg_colors[i]}"

# Queues whose running jobs are always merged into a single coloured block
AGGREGATED_QUEUES = frozenset(
    {"debug", "debug-scaling", "preemptable", "demand", "tiny", "small", "medium"}
)


# ── helpers ─────────────────────────────────────────────────────────────


def _fg(bg_style: str) -> str:
    """Convert ``'on <color>'`` background style to a foreground style."""
    return bg_style.replace("on ", "", 1) if bg_style.startswith("on ") else bg_style


def _job_node_count(job: Job) -> int:
    """Return the best-effort node count for *job*."""
    if exec_nodes := extract_exec_host_nodes(job.exec_host):
        return len(exec_nodes)
    if (count := parse_node_count_spec(job.nodes)) is not None:
        return count
    if requested_nodes := extract_requested_nodes(job.nodes):
        return len(requested_nodes)
    for key in ("select", "nodes", "nodect"):
        if (count := parse_node_count_spec(job.resources_requested.get(key))) is not None:
            return count
    return 1


def _parse_duration_spec(value: Optional[str]) -> Optional[timedelta]:
    if value is None:
        return None
    spec = value.strip()
    if not spec:
        return None
    days = 0
    time_part = spec
    if "-" in spec:
        day_part, remainder = spec.split("-", 1)
        try:
            days = int(day_part)
        except ValueError:
            return None
        time_part = remainder
    parts = time_part.split(":")
    try:
        units = [int(p) for p in parts]
    except ValueError:
        return None
    if len(units) == 3:
        hours, minutes, seconds = units
    elif len(units) == 2:
        hours, minutes, seconds = 0, units[0], units[1]
    elif len(units) == 1:
        hours, minutes, seconds = 0, 0, units[0]
    else:
        return None
    return timedelta(days=days, hours=hours, minutes=minutes, seconds=seconds)


def _time_remaining(job: Job, ref: datetime) -> Optional[timedelta]:
    """Return estimated time remaining for a running job."""
    walltime = _parse_duration_spec(job.walltime)
    if walltime is None:
        return None
    if job.start_time is None:
        return walltime
    start = job.start_time
    end = job.end_time or ref
    if start.tzinfo is not None and end.tzinfo is None:
        end = end.replace(tzinfo=start.tzinfo)
    elif start.tzinfo is None and end.tzinfo is not None:
        start = start.replace(tzinfo=end.tzinfo)
    elapsed = end - start
    remaining = walltime - elapsed
    return timedelta(seconds=0) if remaining.total_seconds() < 0 else remaining


def _format_remaining(td: Optional[timedelta]) -> str:
    if td is None:
        return ""
    total = int(td.total_seconds())
    if total <= 0:
        return "done"
    hours, rem = divmod(total, 3600)
    minutes = rem // 60
    if hours > 0:
        return f"{hours}h{minutes:02d}m"
    return f"{minutes}m"


# ── grid data structure ─────────────────────────────────────────────────


class GridData:
    """Holds the result of building the cluster grid."""

    __slots__ = (
        "header", "grid_text", "legend", "cell_owners", "cell_styles",
        "grid_width", "grid_height",
    )

    def __init__(
        self,
        header: RenderableType,
        grid_text: Text,
        legend: RenderableType,
        cell_owners: List[Optional[str]],
        cell_styles: List[str],
        grid_width: int,
        grid_height: int,
    ) -> None:
        self.header = header
        self.grid_text = grid_text
        self.legend = legend
        self.cell_owners = cell_owners
        self.cell_styles = cell_styles
        self.grid_width = grid_width
        self.grid_height = grid_height


# ── grid building ───────────────────────────────────────────────────────


def _build_grid(
    snapshot: SchedulerSnapshot,
    palette: Palette,
    grid_width: int = 100,
    grid_height: int = 28,
) -> GridData:
    """Build the cluster grid data."""

    total_nodes = max(len(snapshot.nodes), 1)
    total_cells = grid_width * grid_height
    nodes_per_cell = total_nodes / total_cells

    ref = snapshot.timestamp

    running_jobs = [j for j in snapshot.jobs if j.state == "R"]

    # ── partition jobs ──────────────────────────────────────────────
    large_queue_jobs: List[Tuple[Job, int]] = []
    agg_queue_nodes: Dict[str, int] = defaultdict(int)

    for job in running_jobs:
        nc = _job_node_count(job)
        if job.queue in AGGREGATED_QUEUES:
            agg_queue_nodes[job.queue] += nc
        else:
            large_queue_jobs.append((job, nc))

    large_queue_jobs.sort(key=lambda x: x[1], reverse=True)

    # ── assign cells ────────────────────────────────────────────────
    cell_styles: List[str] = [palette.empty_style] * total_cells
    cell_chars: List[str] = ["▒"] * total_cells  # default: textured empty
    cell_owners: List[Optional[str]] = [None] * total_cells
    current = 0

    legend_entries: List[Tuple[str, str, str, int, str]] = []

    for idx, (job, nc) in enumerate(large_queue_jobs):
        style = palette.job_style(idx)
        cells_needed = max(1, int(nc / nodes_per_cell))
        for _ in range(cells_needed):
            if current < total_cells:
                cell_styles[current] = style
                cell_chars[current] = " "  # solid fill for jobs
                cell_owners[current] = job.id
                current += 1
        remaining = _time_remaining(job, ref)
        time_str = _format_remaining(remaining)
        legend_entries.append((style, job.user, job.queue, nc, time_str))

    # Aggregated queues — textured with ░
    agg_legend: List[Tuple[str, str, int]] = []
    for queue_name, nodes in agg_queue_nodes.items():
        style = palette.agg_style(queue_name)
        cells_needed = max(1, int(nodes / nodes_per_cell))
        for _ in range(cells_needed):
            if current < total_cells:
                cell_styles[current] = style
                cell_chars[current] = "░"
                cell_owners[current] = f"queue:{queue_name}"
                current += 1
        agg_legend.append((style, queue_name, nodes))

    # Stats
    running_nodes = sum(nc for _, nc in large_queue_jobs) + sum(agg_queue_nodes.values())
    available_nodes = max(0, total_nodes - running_nodes)
    queued_jobs = sum(1 for j in snapshot.jobs if j.state == "Q")
    utilisation = running_nodes / total_nodes * 100

    # ── header ──────────────────────────────────────────────────────
    ts = ref.astimezone().strftime("%H:%M:%S") if ref.tzinfo else ref.strftime("%H:%M:%S")

    header = Text()
    header.append("Cluster Status ", style="bold")
    header.append(f"[{ts}]", style="dim")
    header.append("  ")
    header.append(
        f"{utilisation:.0f}% ",
        style="bold green" if utilisation < 80 else "bold yellow" if utilisation < 95 else "bold red",
    )
    header.append("utilised", style="dim")
    header.append("  ")
    header.append("Nodes: ", style="dim")
    header.append(f"{total_nodes:,}", style="bold")
    header.append("  Running: ", style="dim")
    header.append(f"{running_nodes:,}", style="bold cyan")
    header.append("  Available: ", style="dim")
    header.append(f"{available_nodes:,}", style="bold green")
    header.append("  Jobs: ", style="dim")
    header.append(f"{len(running_jobs)}", style="bold")
    header.append("R", style="dim green")
    header.append("/", style="dim")
    header.append(f"{queued_jobs}", style="bold")
    header.append("Q", style="dim yellow")

    # ── render grid ─────────────────────────────────────────────────
    grid = Text()
    for row in range(grid_height):
        for col in range(grid_width):
            idx = row * grid_width + col
            grid.append(cell_chars[idx], style=cell_styles[idx])
        if row < grid_height - 1:
            grid.append("\n")

    # ── proportional legend bar ─────────────────────────────────────
    # Each segment's width ∝ its node count.  When a segment is too
    # narrow for its label, a circled number is shown instead and a
    # numbered key is printed below.
    bar_width = grid_width

    # Collect segments: (style, full_label, node_count)
    segments: List[Tuple[str, str, int]] = []
    for style, user, queue, nodes, time_str in legend_entries:
        detail = f"{user} {nodes:,}n {queue}"
        if time_str:
            detail += f" [{time_str}]"
        segments.append((style, detail, nodes))
    for style, queue_name, nodes in agg_legend:
        segments.append((style, f"{queue_name} ({nodes:,}n)", nodes))
    segments.append((palette.empty_style, f"Available ({available_nodes:,}n)", available_nodes))

    # Calculate proportional widths
    remaining_width = bar_width
    remaining_nodes = total_nodes
    seg_widths: List[int] = []
    for _, _, nodes in segments:
        if remaining_nodes <= 0:
            seg_widths.append(0)
            continue
        w = max(1, round(nodes / remaining_nodes * remaining_width)) if nodes > 0 else 0
        seg_widths.append(w)
        remaining_width -= w
        remaining_nodes -= nodes

    # Render the proportional bar — labels inside when they fit, else blank
    legend_bar = Text()
    footnotes: List[Tuple[str, str]] = []  # (style, full_label) for narrow segments

    for (style, label, _), w in zip(segments, seg_widths):
        if w <= 0:
            continue
        if len(label) + 2 <= w:
            pad_left = (w - len(label)) // 2
            pad_right = w - len(label) - pad_left
            legend_bar.append(" " * pad_left, style=style)
            legend_bar.append(label, style=f"bold {style}")
            legend_bar.append(" " * pad_right, style=style)
        else:
            legend_bar.append(" " * w, style=style)
            footnotes.append((style, label))

    # Footnote list for segments too narrow for inline labels
    footnote_text = Text(no_wrap=False)
    if footnotes:
        for style, full_label in footnotes:
            footnote_text.append("  ██", style=_fg(style))
            footnote_text.append(f" {full_label}", style="dim")

    return GridData(
        header=header,
        grid_text=grid,
        legend=Group(legend_bar, footnote_text) if footnotes else legend_bar,
        cell_owners=cell_owners,
        cell_styles=cell_styles,
        grid_width=grid_width,
        grid_height=grid_height,
    )


# ── widgets ─────────────────────────────────────────────────────────────


class _GridPanel(Widget):
    """Interactive coloured grid — supports click to inspect a job."""

    DEFAULT_CSS = """
    _GridPanel {
        border: round $surface-lighten-2;
        height: 1fr;
        min-height: 10;
        padding: 0 1;
    }
    """

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self._content: RenderableType = Text()
        self._cell_owners: List[Optional[str]] = []
        self._cell_styles: List[str] = []
        self._grid_width: int = 0
        self._grid_height: int = 0

    def render(self) -> RenderableType:
        return self._content

    def set_grid(self, data: GridData) -> None:
        self._content = data.grid_text
        self._cell_owners = data.cell_owners
        self._cell_styles = data.cell_styles
        self._grid_width = data.grid_width
        self._grid_height = data.grid_height
        self.refresh()

    def on_click(self, event) -> None:
        if not self._cell_owners or self._grid_width == 0:
            return
        col = int(event.x)
        row = int(event.y)
        if col < 0 or col >= self._grid_width:
            return
        if row < 0 or row >= self._grid_height:
            return
        idx = row * self._grid_width + col
        if idx < 0 or idx >= len(self._cell_owners):
            return
        owner = self._cell_owners[idx]
        if owner:
            style = self._cell_styles[idx] if idx < len(self._cell_styles) else ""
            self.post_message(ClusterGridWidget.CellClicked(owner, style))


class _HeaderPanel(Static):
    """Status header above the grid."""


class _LegendBar(Static):
    """Proportional legend bar below the grid."""


class ClusterGridWidget(VerticalScroll):
    """Cluster-wide node utilization grid with legend.

    Scrollable container. Call :meth:`update_from_snapshot` on each refresh.
    The grid auto-sizes to fill available width; height scales to match.
    """

    class CellClicked(Message):
        """Posted when a grid cell is clicked."""

        def __init__(self, owner: str, color_style: str = "") -> None:
            super().__init__()
            self.owner = owner
            self.color_style = color_style

    DEFAULT_CSS = """
    ClusterGridWidget {
        height: 1fr;
        padding: 1 2;
    }
    ClusterGridWidget _HeaderPanel {
        height: auto;
    }
    ClusterGridWidget _GridPanel {
        height: 1fr;
    }
    ClusterGridWidget _LegendBar {
        height: auto;
        margin-top: 1;
    }
    """

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self._snapshot: Optional[SchedulerSnapshot] = None

    def compose(self):
        yield _HeaderPanel(id="cluster_header")
        yield _GridPanel(id="cluster_grid_panel")
        yield _LegendBar(id="cluster_legend_bar")

    def _rebuild(self) -> None:
        if self._snapshot is None:
            return
        panel = self.query_one(_GridPanel)
        # Use the panel's content area for grid dimensions
        w = panel.size.width - 4 if panel.size.width > 10 else 100
        h = panel.size.height - 2 if panel.size.height > 4 else 14

        # Build palette from current theme
        try:
            theme_vars = self.app.get_css_variables()
        except Exception:
            theme_vars = {}
        pal = _build_palette(theme_vars)

        data = _build_grid(self._snapshot, pal, grid_width=w, grid_height=h)
        self.query_one(_HeaderPanel).update(data.header)
        panel.set_grid(data)
        self.query_one(_LegendBar).update(data.legend)

    def update_from_snapshot(self, snapshot: SchedulerSnapshot) -> None:
        self._snapshot = snapshot
        self._rebuild()

    def on_resize(self, event) -> None:
        self._rebuild()
