name: Release

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v1.2.3
      - v*

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12", "3.13"]
    # Environment and permissions trusted publishing.
    environment:
      # Create this environment in the GitHub repository under Settings -> Environments
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      # - name: Install Python 3.13
      #   run: uv python install 3.13
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.18"
          checksum: "c4c47814a810a2f49016d17d67c559d91c50b4c9"
          activate-environment: true
          python-version: ${{ matrix.python-version }}
      - run: uv pip install pip
      - name: Install pbs-tui
        run: uv pip install -e ".[dev]"
      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
